#server:
#  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
